### ISSUE TITLE
save credentials

### ISSUE THREAD

**Issue by ruslantum** [alexander-schranz/franz-xmpp-client#4]
hi,

is it possible to save locally the credentials, which im supplying to inverse.chat client?

kind regards, ruslantum

**Comment by alexander-schranz** [comment]
@ruslantum this is not issue of the plugin. inverse.chat does also work correctly with saving credentials in browser so you need to create an issue on franz. Think it also have todo with the issue of hipchat where it also don't save the credentials: https://github.com/meetfranz/franz/issues/113.
